services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Set this to 'release' for an optimized build,
        # or 'debug' for faster builds with debug symbols.
        BUILD_TYPE: debug
    ports:
      - 8080:8080
